import type { MarketApp, FeaturedBanner, CategoryInfo } from './app-market.types'

export const CATEGORIES: CategoryInfo[] = [
  { id: 'productivity', label: 'Productivity', icon: '🎯', description: 'Get things done', color: '#0EA5E9' },
  { id: 'utilities', label: 'Utilities', icon: '🔧', description: 'Essential tools', color: '#8B5CF6' },
  { id: 'entertainment', label: 'Entertainment', icon: '🎮', description: 'Fun & games', color: '#F59E0B' },
  { id: 'developer-tools', label: 'Developer Tools', icon: '💻', description: 'Build & deploy', color: '#10B981' },
  { id: 'design', label: 'Design', icon: '🎨', description: 'Create beautiful work', color: '#EC4899' },
  { id: 'education', label: 'Education', icon: '📚', description: 'Learn & grow', color: '#6366F1' },
  { id: 'social', label: 'Social', icon: '💬', description: 'Stay connected', color: '#14B8A6' },
  { id: 'music', label: 'Music', icon: '🎵', description: 'Listen & create', color: '#EF4444' },
]

export const MOCK_APPS: MarketApp[] = [
  {
    id: 'aisu-notes',
    name: 'Aisu Notes',
    developer: 'Aisu Labs',
    icon: '📝',
    category: 'productivity',
    rating: 4.7,
    ratingCount: 1243,
    description: 'Beautiful note-taking with AI-powered organization.',
    longDescription:
      'Aisu Notes brings intelligent note organization to your workflow. Write freely with rich text formatting, embed images and links, and let AI automatically categorize and tag your notes. Features include real-time sync, markdown support, and smart search across all your documents.',
    version: '2.4.1',
    size: '8.2 MB',
    screenshots: [
      { id: 's1', url: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)', caption: 'Editor view' },
      { id: 's2', url: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)', caption: 'Organize' },
      { id: 's3', url: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)', caption: 'AI assist' },
    ],
    reviews: [
      { id: 'r1', author: 'Alex K.', rating: 5, date: '2025-12-01', content: 'Best notes app I have ever used. The AI tagging is incredibly helpful.' },
      { id: 'r2', author: 'Maria S.', rating: 4, date: '2025-11-15', content: 'Great app overall. Wish it had better table support.' },
    ],
    isFeatured: true,
    isInstalled: false,
    price: 'free',
    tags: ['notes', 'ai', 'writing', 'productivity'],
    updatedAt: '2025-12-15',
  },
  {
    id: 'pixel-canvas',
    name: 'Pixel Canvas',
    developer: 'Creative Co.',
    icon: '🎨',
    category: 'design',
    rating: 4.5,
    ratingCount: 876,
    description: 'Professional pixel art editor with animation tools.',
    longDescription:
      'Pixel Canvas is a full-featured pixel art editor designed for game developers and artists. Create sprites, tilesets, and animations with an intuitive toolset. Export to PNG, GIF, or sprite sheets. Includes 50+ color palettes and onion skinning for smooth animations.',
    version: '3.1.0',
    size: '12.4 MB',
    screenshots: [
      { id: 's1', url: 'linear-gradient(135deg, #a18cd1 0%, #fbc2eb 100%)', caption: 'Canvas' },
      { id: 's2', url: 'linear-gradient(135deg, #ffecd2 0%, #fcb69f 100%)', caption: 'Palettes' },
    ],
    reviews: [
      { id: 'r1', author: 'Jake R.', rating: 5, date: '2025-10-20', content: 'Perfect for game sprites. Animation timeline is top-notch.' },
      { id: 'r2', author: 'Lily T.', rating: 4, date: '2025-09-10', content: 'Love the palette system. Could use more brush options.' },
    ],
    isFeatured: true,
    isInstalled: false,
    price: '$4.99',
    tags: ['pixel-art', 'design', 'animation', 'sprites'],
    updatedAt: '2025-11-20',
  },
  {
    id: 'code-forge',
    name: 'Code Forge',
    developer: 'DevStack Inc.',
    icon: '⚡',
    category: 'developer-tools',
    rating: 4.8,
    ratingCount: 2105,
    description: 'Lightning-fast code editor with AI completion.',
    longDescription:
      'Code Forge is a modern code editor built for speed. Features AI-powered code completion, multi-cursor editing, integrated terminal, and Git support. Supports 40+ programming languages with syntax highlighting and intelligent formatting.',
    version: '1.8.3',
    size: '24.1 MB',
    screenshots: [
      { id: 's1', url: 'linear-gradient(135deg, #0c0c0c 0%, #1a1a2e 100%)', caption: 'Editor' },
      { id: 's2', url: 'linear-gradient(135deg, #16213e 0%, #0f3460 100%)', caption: 'Terminal' },
      { id: 's3', url: 'linear-gradient(135deg, #1a1a2e 0%, #533483 100%)', caption: 'Git view' },
    ],
    reviews: [
      { id: 'r1', author: 'Sam D.', rating: 5, date: '2025-12-10', content: 'Replaced my main editor. AI completions are scary good.' },
      { id: 'r2', author: 'Nina P.', rating: 5, date: '2025-11-28', content: 'Fast, clean, powerful. What more could you want?' },
    ],
    isFeatured: true,
    isInstalled: true,
    price: 'free',
    tags: ['code', 'editor', 'ai', 'developer'],
    updatedAt: '2025-12-10',
  },
  {
    id: 'sound-wave',
    name: 'Sound Wave',
    developer: 'AudioLab',
    icon: '🎧',
    category: 'music',
    rating: 4.3,
    ratingCount: 654,
    description: 'Music player with visualizer and equalizer.',
    longDescription:
      'Sound Wave delivers a premium music listening experience with real-time audio visualization, 10-band equalizer, and gapless playback. Organize your library by albums, artists, or playlists. Supports MP3, FLAC, WAV, and OGG formats.',
    version: '2.0.5',
    size: '6.8 MB',
    screenshots: [
      { id: 's1', url: 'linear-gradient(135deg, #ed6ea0 0%, #ec8c69 100%)', caption: 'Now playing' },
      { id: 's2', url: 'linear-gradient(135deg, #ee9ca7 0%, #ffdde1 100%)', caption: 'Library' },
    ],
    reviews: [
      { id: 'r1', author: 'Tom H.', rating: 4, date: '2025-10-05', content: 'Great visualizer. Equalizer presets are really useful.' },
    ],
    isInstalled: false,
    price: 'free',
    tags: ['music', 'player', 'audio', 'equalizer'],
    updatedAt: '2025-10-15',
  },
  {
    id: 'task-flow',
    name: 'Task Flow',
    developer: 'Productiv',
    icon: '✅',
    category: 'productivity',
    rating: 4.6,
    ratingCount: 1890,
    description: 'Kanban boards and task management made simple.',
    longDescription:
      'Task Flow helps you organize work with kanban boards, lists, and calendar views. Drag and drop tasks between columns, set due dates, assign labels, and track progress. Supports team collaboration with shared boards and real-time updates.',
    version: '4.2.0',
    size: '5.1 MB',
    screenshots: [
      { id: 's1', url: 'linear-gradient(135deg, #89f7fe 0%, #66a6ff 100%)', caption: 'Board view' },
      { id: 's2', url: 'linear-gradient(135deg, #c3cfe2 0%, #f5f7fa 100%)', caption: 'Calendar' },
    ],
    reviews: [
      { id: 'r1', author: 'Chris W.', rating: 5, date: '2025-11-20', content: 'Simple yet powerful. The drag and drop is buttery smooth.' },
      { id: 'r2', author: 'Ava L.', rating: 4, date: '2025-10-30', content: 'Good for personal projects. Would love Gantt charts.' },
    ],
    isInstalled: false,
    price: 'free',
    tags: ['tasks', 'kanban', 'productivity', 'project'],
    updatedAt: '2025-11-25',
  },
  {
    id: 'sys-monitor',
    name: 'Sys Monitor',
    developer: 'DevStack Inc.',
    icon: '📊',
    category: 'utilities',
    rating: 4.4,
    ratingCount: 432,
    description: 'Real-time system resource monitoring dashboard.',
    longDescription:
      'Sys Monitor provides real-time insights into your system performance. Monitor CPU, memory, disk, and network usage with beautiful charts. Set alerts for high resource usage and view historical data to identify trends.',
    version: '1.5.2',
    size: '3.4 MB',
    screenshots: [
      { id: 's1', url: 'linear-gradient(135deg, #2b5876 0%, #4e4376 100%)', caption: 'Dashboard' },
      { id: 's2', url: 'linear-gradient(135deg, #0f2027 0%, #203a43 50%, #2c5364 100%)', caption: 'Processes' },
    ],
    reviews: [
      { id: 'r1', author: 'Dev M.', rating: 5, date: '2025-09-15', content: 'Clean and informative. The charts are really well designed.' },
    ],
    isInstalled: false,
    price: 'free',
    tags: ['system', 'monitor', 'performance', 'utility'],
    updatedAt: '2025-09-20',
  },
  {
    id: 'chat-hub',
    name: 'Chat Hub',
    developer: 'SocialNet',
    icon: '💬',
    category: 'social',
    rating: 4.2,
    ratingCount: 3210,
    description: 'Unified messaging for all your chat platforms.',
    longDescription:
      'Chat Hub brings all your conversations into one place. Connect accounts from multiple platforms and manage all messages from a single interface. Features include message search, file sharing, and notification management.',
    version: '3.0.1',
    size: '11.2 MB',
    screenshots: [
      { id: 's1', url: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)', caption: 'Chats' },
      { id: 's2', url: 'linear-gradient(135deg, #9b59b6 0%, #3498db 100%)', caption: 'Settings' },
    ],
    reviews: [
      { id: 'r1', author: 'Emma R.', rating: 4, date: '2025-12-05', content: 'So convenient to have everything in one app.' },
      { id: 'r2', author: 'Luis G.', rating: 4, date: '2025-11-18', content: 'Works well. Notification sync could be better.' },
    ],
    isInstalled: false,
    price: 'free',
    tags: ['chat', 'messaging', 'social', 'communication'],
    updatedAt: '2025-12-08',
  },
  {
    id: 'retro-arcade',
    name: 'Retro Arcade',
    developer: 'PixelFun Games',
    icon: '👾',
    category: 'entertainment',
    rating: 4.1,
    ratingCount: 987,
    description: 'Classic arcade games collection with leaderboards.',
    longDescription:
      'Retro Arcade brings classic arcade gaming to your desktop. Enjoy a curated collection of retro-style games including Snake, Tetris-like puzzles, Breakout, and more. Compete on global leaderboards and unlock achievements.',
    version: '1.3.0',
    size: '15.7 MB',
    screenshots: [
      { id: 's1', url: 'linear-gradient(135deg, #f5af19 0%, #f12711 100%)', caption: 'Game select' },
      { id: 's2', url: 'linear-gradient(135deg, #1a2a6c 0%, #b21f1f 50%, #fdbb2d 100%)', caption: 'Gameplay' },
    ],
    reviews: [
      { id: 'r1', author: 'Ryan K.', rating: 4, date: '2025-10-25', content: 'Great nostalgia trip. The Snake game is addictive.' },
    ],
    isInstalled: false,
    price: '$1.99',
    tags: ['games', 'arcade', 'retro', 'entertainment'],
    updatedAt: '2025-10-30',
  },
  {
    id: 'flash-cards',
    name: 'Flash Cards',
    developer: 'EduTech',
    icon: '🧠',
    category: 'education',
    rating: 4.6,
    ratingCount: 756,
    description: 'Spaced repetition flashcards for effective learning.',
    longDescription:
      'Flash Cards uses spaced repetition algorithms to optimize your learning. Create custom decks or choose from a library of pre-made sets. Track your progress with detailed statistics and streaks. Supports text, images, and audio cards.',
    version: '2.1.0',
    size: '4.3 MB',
    screenshots: [
      { id: 's1', url: 'linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%)', caption: 'Study' },
      { id: 's2', url: 'linear-gradient(135deg, #a78bfa 0%, #c4b5fd 100%)', caption: 'Stats' },
    ],
    reviews: [
      { id: 'r1', author: 'Sophie L.', rating: 5, date: '2025-11-10', content: 'The spaced repetition really works. My retention improved so much.' },
      { id: 'r2', author: 'Karim A.', rating: 4, date: '2025-10-22', content: 'Solid flashcard app. Deck sharing would be a nice addition.' },
    ],
    isInstalled: false,
    price: 'free',
    tags: ['education', 'flashcards', 'learning', 'study'],
    updatedAt: '2025-11-15',
  },
  {
    id: 'clip-vault',
    name: 'Clip Vault',
    developer: 'Productiv',
    icon: '📋',
    category: 'utilities',
    rating: 4.5,
    ratingCount: 543,
    description: 'Clipboard manager with history and snippets.',
    longDescription:
      'Clip Vault keeps a searchable history of everything you copy. Pin frequently used snippets for quick access, organize with folders, and sync across windows. Supports text, images, and code blocks with syntax highlighting.',
    version: '1.9.0',
    size: '2.8 MB',
    screenshots: [
      { id: 's1', url: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)', caption: 'History' },
      { id: 's2', url: 'linear-gradient(135deg, #43e97b 0%, #38f9d7 100%)', caption: 'Snippets' },
    ],
    reviews: [
      { id: 'r1', author: 'Dan F.', rating: 5, date: '2025-12-02', content: 'Can\'t live without it now. The search is incredibly fast.' },
    ],
    isInstalled: true,
    price: 'free',
    tags: ['clipboard', 'utility', 'snippets', 'productivity'],
    updatedAt: '2025-12-05',
  },
  {
    id: 'api-tester',
    name: 'API Tester',
    developer: 'DevStack Inc.',
    icon: '🔌',
    category: 'developer-tools',
    rating: 4.7,
    ratingCount: 1320,
    description: 'REST & GraphQL API testing with collections.',
    longDescription:
      'API Tester makes it easy to test and debug APIs. Send requests with custom headers, body, and auth. Organize endpoints into collections, write test scripts, and generate documentation. Supports REST, GraphQL, and WebSocket protocols.',
    version: '2.6.0',
    size: '9.5 MB',
    screenshots: [
      { id: 's1', url: 'linear-gradient(135deg, #0f0c29 0%, #302b63 50%, #24243e 100%)', caption: 'Request builder' },
      { id: 's2', url: 'linear-gradient(135deg, #141e30 0%, #243b55 100%)', caption: 'Response' },
    ],
    reviews: [
      { id: 'r1', author: 'Pat O.', rating: 5, date: '2025-11-30', content: 'Clean interface and very fast. Collections feature is a lifesaver.' },
      { id: 'r2', author: 'Yuki T.', rating: 4, date: '2025-11-10', content: 'Great for REST APIs. GraphQL support could use more features.' },
    ],
    isFeatured: true,
    isInstalled: false,
    price: 'free',
    tags: ['api', 'testing', 'developer', 'rest', 'graphql'],
    updatedAt: '2025-12-01',
  },
  {
    id: 'weather-live',
    name: 'Weather Live',
    developer: 'Aisu Labs',
    icon: '🌤️',
    category: 'utilities',
    rating: 4.0,
    ratingCount: 1120,
    description: 'Beautiful weather forecasts with live animations.',
    longDescription:
      'Weather Live shows current conditions and forecasts with stunning animated backgrounds. Get hourly and 10-day forecasts, severe weather alerts, and radar maps. Supports multiple locations with quick switching.',
    version: '3.2.1',
    size: '7.6 MB',
    screenshots: [
      { id: 's1', url: 'linear-gradient(135deg, #74b9ff 0%, #0984e3 100%)', caption: 'Current' },
      { id: 's2', url: 'linear-gradient(135deg, #a29bfe 0%, #6c5ce7 100%)', caption: 'Forecast' },
    ],
    reviews: [
      { id: 'r1', author: 'Mia J.', rating: 4, date: '2025-09-28', content: 'Beautiful design. Animations are a nice touch.' },
    ],
    isInstalled: false,
    price: 'free',
    tags: ['weather', 'forecast', 'utility'],
    updatedAt: '2025-10-01',
  },
  {
    id: 'sketch-pad',
    name: 'Sketch Pad',
    developer: 'Creative Co.',
    icon: '✏️',
    category: 'design',
    rating: 4.3,
    ratingCount: 678,
    description: 'Quick sketching and whiteboard tool.',
    longDescription:
      'Sketch Pad is a lightweight drawing tool for quick sketches, wireframes, and brainstorming. Features pressure-sensitive brush, shape tools, layers, and export to PNG/SVG. Perfect for rapid prototyping and visual thinking.',
    version: '1.4.2',
    size: '4.9 MB',
    screenshots: [
      { id: 's1', url: 'linear-gradient(135deg, #ffecd2 0%, #fcb69f 100%)', caption: 'Canvas' },
      { id: 's2', url: 'linear-gradient(135deg, #ff9a9e 0%, #fecfef 100%)', caption: 'Tools' },
    ],
    reviews: [
      { id: 'r1', author: 'Zara N.', rating: 4, date: '2025-11-05', content: 'Simple and fast. Great for quick wireframes.' },
    ],
    isInstalled: false,
    price: '$2.99',
    tags: ['drawing', 'sketch', 'design', 'whiteboard'],
    updatedAt: '2025-11-10',
  },
  {
    id: 'focus-timer',
    name: 'Focus Timer',
    developer: 'Productiv',
    icon: '⏱️',
    category: 'productivity',
    rating: 4.4,
    ratingCount: 890,
    description: 'Pomodoro timer with ambient sounds and stats.',
    longDescription:
      'Focus Timer helps you maintain concentration with the Pomodoro technique. Set custom work and break intervals, play ambient sounds, and track your daily focus hours. Integrates with Task Flow for seamless workflow.',
    version: '2.0.0',
    size: '3.2 MB',
    screenshots: [
      { id: 's1', url: 'linear-gradient(135deg, #fa709a 0%, #fee140 100%)', caption: 'Timer' },
      { id: 's2', url: 'linear-gradient(135deg, #a8edea 0%, #fed6e3 100%)', caption: 'Statistics' },
    ],
    reviews: [
      { id: 'r1', author: 'Ben C.', rating: 5, date: '2025-12-12', content: 'The ambient sounds are really relaxing. Keeps me focused.' },
      { id: 'r2', author: 'Isa M.', rating: 4, date: '2025-11-29', content: 'Good pomodoro app. Daily stats help me stay motivated.' },
    ],
    isInstalled: false,
    price: 'free',
    tags: ['timer', 'pomodoro', 'focus', 'productivity'],
    updatedAt: '2025-12-12',
  },
  {
    id: 'quiz-master',
    name: 'Quiz Master',
    developer: 'EduTech',
    icon: '❓',
    category: 'education',
    rating: 4.2,
    ratingCount: 445,
    description: 'Create and take quizzes on any subject.',
    longDescription:
      'Quiz Master lets you create custom quizzes with multiple choice, true/false, and open-ended questions. Share quizzes with others, compete on leaderboards, and track your learning progress over time.',
    version: '1.7.0',
    size: '5.5 MB',
    screenshots: [
      { id: 's1', url: 'linear-gradient(135deg, #ff758c 0%, #ff7eb3 100%)', caption: 'Quiz' },
      { id: 's2', url: 'linear-gradient(135deg, #f77062 0%, #fe5196 100%)', caption: 'Results' },
    ],
    reviews: [
      { id: 'r1', author: 'Lin W.', rating: 4, date: '2025-10-18', content: 'Fun way to study. Love the competitive leaderboards.' },
    ],
    isInstalled: false,
    price: 'free',
    tags: ['quiz', 'education', 'learning', 'trivia'],
    updatedAt: '2025-10-25',
  },
]

export const FEATURED_BANNERS: FeaturedBanner[] = [
  {
    id: 'f1',
    appId: 'aisu-notes',
    title: 'Write smarter with AI',
    subtitle: 'Aisu Notes brings intelligent organization to your workflow',
    gradient: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
  },
  {
    id: 'f2',
    appId: 'code-forge',
    title: 'Code at lightning speed',
    subtitle: 'AI-powered completions that understand your codebase',
    gradient: 'linear-gradient(135deg, #0f0c29 0%, #302b63 50%, #24243e 100%)',
  },
  {
    id: 'f3',
    appId: 'pixel-canvas',
    title: 'Pixel art reimagined',
    subtitle: 'Create stunning sprites and animations with powerful tools',
    gradient: 'linear-gradient(135deg, #a18cd1 0%, #fbc2eb 100%)',
  },
  {
    id: 'f4',
    appId: 'api-tester',
    title: 'Test APIs effortlessly',
    subtitle: 'Collections, scripts, and documentation in one place',
    gradient: 'linear-gradient(135deg, #141e30 0%, #243b55 100%)',
  },
]

export const TOP_CHART_LIMIT = 6
