import type { FileNode } from '@/types'
import type { ContextMenuItem } from '@/types/desktop'
import type { SidebarFavorite, SidebarTag } from './file-manager.types'

export const MOCK_FILE_SYSTEM: FileNode = {
  name: '/',
  path: '/',
  type: 'directory',
  children: [
    {
      name: 'Desktop',
      path: '/Desktop',
      type: 'directory',
      updatedAt: new Date('2025-06-02'),
      children: [
        {
          name: 'Projects',
          path: '/Desktop/Projects',
          type: 'directory',
          updatedAt: new Date('2025-06-01'),
          children: [
            {
              name: 'aiso-web',
              path: '/Desktop/Projects/aiso-web',
              type: 'directory',
              updatedAt: new Date('2025-06-01'),
              children: [
                {
                  name: 'package.json',
                  path: '/Desktop/Projects/aiso-web/package.json',
                  type: 'file',
                  size: 892,
                  mimeType: 'application/json',
                  updatedAt: new Date('2025-06-01'),
                },
                {
                  name: 'src',
                  path: '/Desktop/Projects/aiso-web/src',
                  type: 'directory',
                  updatedAt: new Date('2025-06-01'),
                  children: [
                    {
                      name: 'App.tsx',
                      path: '/Desktop/Projects/aiso-web/src/App.tsx',
                      type: 'file',
                      size: 2400,
                      mimeType: 'text/typescript',
                      updatedAt: new Date('2025-06-01'),
                    },
                    {
                      name: 'index.css',
                      path: '/Desktop/Projects/aiso-web/src/index.css',
                      type: 'file',
                      size: 180,
                      mimeType: 'text/css',
                      updatedAt: new Date('2025-05-28'),
                    },
                  ],
                },
                {
                  name: 'README.md',
                  path: '/Desktop/Projects/aiso-web/README.md',
                  type: 'file',
                  size: 2500,
                  mimeType: 'text/markdown',
                  updatedAt: new Date('2025-05-20'),
                },
                {
                  name: 'tsconfig.json',
                  path: '/Desktop/Projects/aiso-web/tsconfig.json',
                  type: 'file',
                  size: 540,
                  mimeType: 'application/json',
                  updatedAt: new Date('2025-05-18'),
                },
              ],
            },
            {
              name: 'notes-app',
              path: '/Desktop/Projects/notes-app',
              type: 'directory',
              updatedAt: new Date('2025-05-10'),
              children: [
                {
                  name: 'index.html',
                  path: '/Desktop/Projects/notes-app/index.html',
                  type: 'file',
                  size: 1200,
                  mimeType: 'text/html',
                  updatedAt: new Date('2025-05-10'),
                },
                {
                  name: 'style.css',
                  path: '/Desktop/Projects/notes-app/style.css',
                  type: 'file',
                  size: 3400,
                  mimeType: 'text/css',
                  updatedAt: new Date('2025-05-09'),
                },
              ],
            },
          ],
        },
        {
          name: 'screenshot.png',
          path: '/Desktop/screenshot.png',
          type: 'file',
          size: 2_400_000,
          mimeType: 'image/png',
          updatedAt: new Date('2025-05-15'),
        },
        {
          name: 'notes.txt',
          path: '/Desktop/notes.txt',
          type: 'file',
          size: 1240,
          mimeType: 'text/plain',
          updatedAt: new Date('2025-06-02'),
        },
      ],
    },
    {
      name: 'Documents',
      path: '/Documents',
      type: 'directory',
      updatedAt: new Date('2025-04-15'),
      children: [
        {
          name: 'Resume.pdf',
          path: '/Documents/Resume.pdf',
          type: 'file',
          size: 245_000,
          mimeType: 'application/pdf',
          updatedAt: new Date('2025-04-10'),
        },
        {
          name: 'Budget 2025.xlsx',
          path: '/Documents/Budget 2025.xlsx',
          type: 'file',
          size: 34_000,
          mimeType: 'application/vnd.ms-excel',
          updatedAt: new Date('2025-03-22'),
        },
        {
          name: 'Meeting Notes',
          path: '/Documents/Meeting Notes',
          type: 'directory',
          updatedAt: new Date('2025-04-15'),
          children: [
            {
              name: 'Q1 Review.md',
              path: '/Documents/Meeting Notes/Q1 Review.md',
              type: 'file',
              size: 4500,
              mimeType: 'text/markdown',
              updatedAt: new Date('2025-03-31'),
            },
            {
              name: 'Q2 Planning.md',
              path: '/Documents/Meeting Notes/Q2 Planning.md',
              type: 'file',
              size: 3200,
              mimeType: 'text/markdown',
              updatedAt: new Date('2025-04-15'),
            },
          ],
        },
        {
          name: 'Contracts',
          path: '/Documents/Contracts',
          type: 'directory',
          updatedAt: new Date('2025-02-20'),
          children: [
            {
              name: 'NDA.pdf',
              path: '/Documents/Contracts/NDA.pdf',
              type: 'file',
              size: 120_000,
              mimeType: 'application/pdf',
              updatedAt: new Date('2025-02-20'),
            },
          ],
        },
      ],
    },
    {
      name: 'Downloads',
      path: '/Downloads',
      type: 'directory',
      updatedAt: new Date('2025-06-01'),
      children: [
        {
          name: 'installer.dmg',
          path: '/Downloads/installer.dmg',
          type: 'file',
          size: 85_000_000,
          mimeType: 'application/x-apple-diskimage',
          updatedAt: new Date('2025-05-28'),
        },
        {
          name: 'photo-collection.zip',
          path: '/Downloads/photo-collection.zip',
          type: 'file',
          size: 12_500_000,
          mimeType: 'application/zip',
          updatedAt: new Date('2025-05-30'),
        },
        {
          name: 'presentation.pptx',
          path: '/Downloads/presentation.pptx',
          type: 'file',
          size: 5_200_000,
          mimeType: 'application/vnd.ms-powerpoint',
          updatedAt: new Date('2025-06-01'),
        },
        {
          name: 'report.pdf',
          path: '/Downloads/report.pdf',
          type: 'file',
          size: 890_000,
          mimeType: 'application/pdf',
          updatedAt: new Date('2025-05-25'),
        },
      ],
    },
    {
      name: 'Pictures',
      path: '/Pictures',
      type: 'directory',
      updatedAt: new Date('2025-05-01'),
      children: [
        {
          name: 'Wallpapers',
          path: '/Pictures/Wallpapers',
          type: 'directory',
          updatedAt: new Date('2025-02-14'),
          children: [
            {
              name: 'mountain.jpg',
              path: '/Pictures/Wallpapers/mountain.jpg',
              type: 'file',
              size: 3_200_000,
              mimeType: 'image/jpeg',
              updatedAt: new Date('2025-02-14'),
            },
            {
              name: 'ocean.jpg',
              path: '/Pictures/Wallpapers/ocean.jpg',
              type: 'file',
              size: 2_800_000,
              mimeType: 'image/jpeg',
              updatedAt: new Date('2025-02-14'),
            },
            {
              name: 'aurora.png',
              path: '/Pictures/Wallpapers/aurora.png',
              type: 'file',
              size: 5_100_000,
              mimeType: 'image/png',
              updatedAt: new Date('2025-01-20'),
            },
          ],
        },
        {
          name: 'Screenshots',
          path: '/Pictures/Screenshots',
          type: 'directory',
          updatedAt: new Date('2025-05-01'),
          children: [
            {
              name: 'Screen Shot 2025-05-01.png',
              path: '/Pictures/Screenshots/Screen Shot 2025-05-01.png',
              type: 'file',
              size: 1_800_000,
              mimeType: 'image/png',
              updatedAt: new Date('2025-05-01'),
            },
          ],
        },
        {
          name: 'avatar.png',
          path: '/Pictures/avatar.png',
          type: 'file',
          size: 450_000,
          mimeType: 'image/png',
          updatedAt: new Date('2025-04-20'),
        },
      ],
    },
    {
      name: 'Music',
      path: '/Music',
      type: 'directory',
      updatedAt: new Date('2025-05-10'),
      children: [
        {
          name: 'playlist.m3u',
          path: '/Music/playlist.m3u',
          type: 'file',
          size: 2400,
          mimeType: 'audio/x-mpegurl',
          updatedAt: new Date('2025-05-10'),
        },
        {
          name: 'lofi-beats.mp3',
          path: '/Music/lofi-beats.mp3',
          type: 'file',
          size: 8_400_000,
          mimeType: 'audio/mpeg',
          updatedAt: new Date('2025-04-01'),
        },
        {
          name: 'jazz-collection.mp3',
          path: '/Music/jazz-collection.mp3',
          type: 'file',
          size: 12_000_000,
          mimeType: 'audio/mpeg',
          updatedAt: new Date('2025-03-15'),
        },
      ],
    },
    {
      name: 'Videos',
      path: '/Videos',
      type: 'directory',
      updatedAt: new Date('2025-06-01'),
      children: [
        {
          name: 'tutorial.mp4',
          path: '/Videos/tutorial.mp4',
          type: 'file',
          size: 125_000_000,
          mimeType: 'video/mp4',
          updatedAt: new Date('2025-05-20'),
        },
        {
          name: 'demo-recording.mov',
          path: '/Videos/demo-recording.mov',
          type: 'file',
          size: 48_000_000,
          mimeType: 'video/quicktime',
          updatedAt: new Date('2025-06-01'),
        },
      ],
    },
  ],
}

export const SIDEBAR_FAVORITES: SidebarFavorite[] = [
  { label: 'Desktop', path: '/Desktop', icon: 'desktop' },
  { label: 'Documents', path: '/Documents', icon: 'documents' },
  { label: 'Downloads', path: '/Downloads', icon: 'downloads' },
  { label: 'Pictures', path: '/Pictures', icon: 'pictures' },
  { label: 'Music', path: '/Music', icon: 'music' },
  { label: 'Videos', path: '/Videos', icon: 'videos' },
]

export const SIDEBAR_TAGS: SidebarTag[] = [
  { label: 'Red', color: '#FF3B30' },
  { label: 'Orange', color: '#FF9500' },
  { label: 'Yellow', color: '#FFCC00' },
  { label: 'Green', color: '#34C759' },
  { label: 'Blue', color: '#007AFF' },
  { label: 'Purple', color: '#AF52DE' },
]

export const FILE_CONTEXT_MENU: ContextMenuItem[] = [
  { label: 'Open', action: 'open' },
  { label: 'Open With...', disabled: true },
  { label: '', separator: true },
  { label: 'Get Info', shortcut: '⌘I' },
  { label: 'Rename', action: 'rename' },
  { label: '', separator: true },
  { label: 'Copy', shortcut: '⌘C' },
  { label: 'Duplicate', shortcut: '⌘D' },
  { label: '', separator: true },
  { label: 'Move to Trash', shortcut: '⌘⌫' },
]

export const DIRECTORY_CONTEXT_MENU: ContextMenuItem[] = [
  { label: 'Open', action: 'open' },
  { label: 'Open in New Tab', disabled: true },
  { label: '', separator: true },
  { label: 'Get Info', shortcut: '⌘I' },
  { label: 'Rename', action: 'rename' },
  { label: '', separator: true },
  { label: 'Copy', shortcut: '⌘C' },
  { label: 'Duplicate', shortcut: '⌘D' },
  { label: '', separator: true },
  { label: 'Move to Trash', shortcut: '⌘⌫' },
]

export const BACKGROUND_CONTEXT_MENU: ContextMenuItem[] = [
  { label: 'New Folder', shortcut: '⇧⌘N', action: 'new-folder' },
  { label: 'New File', action: 'new-file' },
  { label: '', separator: true },
  { label: 'Get Info', shortcut: '⌘I' },
  { label: '', separator: true },
  { label: 'Sort By', disabled: true },
  { label: 'Clean Up Selection' },
  { label: '', separator: true },
  { label: 'Select All', shortcut: '⌘A' },
]
